language: python
python:
  - 3.5
  - 3.6
  - 3.7
install:
  - pip install --upgrade setuptools pip wheel
  - pip install codecov
  - pip install -r requirements-dev.txt
  - pip install '.'
script:
  - flake8 --statistics wisestork tests
  - coverage run --source=wisestork -m py.test -v test
  - coverage xml
  - coverage report -m
after_success:
  - codecov