language: python
python:
  - 3.4
install:
  - pip install --upgrade setuptools pip wheel
  - pip install -r requirements.txt
  - pip install coveralls --use-wheel
script: python setup.py develop && py.test -v --cov wiseguy --cov-report term-missing
after_success:
  - coveralls